config/routes.rb
Portfolio::Application.routes.draw do

  resources :dividends

  resources :cover_buys

  resources :short_sells

  resources :sells

  resources :buys

  resources :stocks

  resources :categories

  get "pages/home"
	root :to => 'pages#home'

end

app/models/short_sell.rb
class ShortSell < ActiveRecord::Base
  belongs_to :stock
  # attr_accessible :chart, :date, :fee, :kind, :net, :price, :qty, :status, :stock_id, :vat
  default_scope { (order'date ASC') }
  mount_uploader :chart, ImageUploader  
  
	validates_presence_of :stock_id 
	validates_numericality_of :qty, :price
	before_create :assign_values	
	before_update :assign_values

  # Getter
  def amount
		qty * price
  end 
	
	private
	def assign_values
		self.fee = (self.qty * self.price) * 0.002070;
		self.vat = self.fee * 0.07;
		self.net = (self.qty * self.price) - self.fee - self.vat;
		if self.status != 'Bought'
			self.status = 'Active'
		end			
	end   
end

app/controllers/short_sells_controller.rb
class ShortSellsController < ApplicationController
  before_action :set_short_sell, only: [:show, :edit, :update, :destroy]

  # GET /short_sells
  # GET /short_sells.json
  def index
    @short_sells = ShortSell.all
  end

  # GET /short_sells/1
  # GET /short_sells/1.json
  def show
  end

  # GET /short_sells/new
  def new
    @short_sell = ShortSell.new
  end

  # GET /short_sells/1/edit
  def edit
  end

  # POST /short_sells
  # POST /short_sells.json
  def create
    @short_sell = ShortSell.new(short_sell_params)

    respond_to do |format|
      if @short_sell.save
        format.html { redirect_to @short_sell, notice: 'Short sell was successfully created.' }
        format.json { render json: @short_sell, status: :created, location: @short_sell }
      else
        format.html { render action: "new" }
        format.json { render json: @short_sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /short_sells/1
  # PUT /short_sells/1.json
  def update
    respond_to do |format|
      if @short_sell.update(short_sell_params)
        format.html { redirect_to @short_sell, notice: 'Short sell was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @short_sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_sells/1
  # DELETE /short_sells/1.json
  def destroy
    @short_sell.destroy
    respond_to do |format|
      format.html { redirect_to short_sells_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_sell
      @short_sell = ShortSell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_sell_params
      params.require(:short_sell).permit(:chart, :date, :fee, :kind, :net, :price, :qty, :status, :stock_id, :vat)
    end  
end

app/helpers/short_sells_helper.rb
module ShortSellsHelper
end

app/views/short_sells/_form.html.erb
<%= form_for(@short_sell) do |f| %>
  <% if @short_sell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short_sell.errors.count, "error") %> prohibited this short_sell from being saved:</h2>

      <ul>
      <% @short_sell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock %><br />
    <%= f.collection_select :stock_id, Stock.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :qty %><br />
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :chart %><br />
    <%= f.file_field :chart %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/short_sells/edit.html.erb
<h1>Editing short_sell</h1>

<%= render 'form' %>

<%= link_to 'Show', @short_sell %> |
<%= link_to 'Back', short_sells_path %>

app/views/short_sells/index.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_short_sell_path %></li>
<% end %>
<%= currently_at 'Short Sells'%>

<h1>Listing short_sells</h1>

<table id="short_sells" class="display">
<thead>
  <tr>
    <th>Status</th>     
    <th>Stock</th>
    <th>Category</th>    
    <th>Sell Date</th>
    <th>Days</th>    
    <th>Qty</th>
    <th>Price</th>
    <th>Amount</th>  
    <th>Net</th>        
    <th>Kind</th>    
    <th>Id</th>   
    <th>Buy</th>          
  </tr>
</thead>
<tbody>
<% @short_sells.each do |short_sell| %>
  <tr>
    <td><%= short_sell.status %></td>      
    <td><%= link_to(short_sell.stock.name, short_sell) %></td>
    <td><%= short_sell.stock.category.name %></td>    
    <td><%= short_sell.date %></td>
    <td><%= (Date.today - short_sell.date).to_i %></td>    
    <td><%= number_with_delimiter(short_sell.qty) %></td>
    <td><%= number_to_currency(short_sell.price) %></td>    
    <td><%= number_to_currency(short_sell.amount) %></td>       
    <td><%= number_to_currency(short_sell.net) %></td>    
   <td><%= short_sell.kind %></td>  
   <td><%= short_sell.id %></td>       
   <td><%= link_to 'Buy', new_cover_buy_path(:param1 => short_sell.id) %>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Short sell', new_short_sell_path %>

app/views/short_sells/new.html.erb
<h1>New short_sell</h1>

<%= render 'form' %>

<%= link_to 'Back', short_sells_path %>

app/views/short_sells/show.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_short_sell_path %></li>
<li><%= link_to 'Edit', edit_short_sell_path(@short_sell) %></li>
<li><%= link_to 'Back', short_sells_path %></li>
<li><%= link_to 'Destroy', @short_sell, method: :delete, data: { confirm: 'Are you sure?' } %></li>

<% end %>
<%= currently_at 'short_sells'%>

<p>
  <b>Stock:</b>
  <%= @short_sell.stock.name %>
</p>

<p>
  <b>Date:</b>
  <%= @short_sell.date %>
</p>

<p>
  <b>Qty:</b>
  <%= number_with_delimiter(@short_sell.qty) %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@short_sell.price) %>
</p>

<p>
  <b>Fee:</b>
  <%= number_to_currency(@short_sell.fee) %>
</p>

<p>
  <b>VAT:</b>
  <%= @short_sell.vat %>
</p>
<p>
  <b>Net:</b>
  <%= number_to_currency(@short_sell.net) %>
</p>
<p>
  <b>Status:</b>
  <%= @short_sell.status %>
</p>
<p>
  <b>Kind:</b>
  <%= @short_sell.kind %>
</p>
<p>
   <%= image_tag @short_sell.chart_url.to_s %>
</p>

   
<%= link_to 'Edit', edit_short_sell_path(@short_sell) %> |
<%= link_to 'Back', short_sells_path %>