config/routes.rb
Portfolio::Application.routes.draw do

  resources :dividends

  resources :cover_buys

  resources :short_sells

  resources :sells

  resources :buys

  resources :stocks

  resources :categories

  get "pages/home"
	root :to => 'pages#home'

end

app/models/buy.rb
class Buy < ActiveRecord::Base
  # attr_accessible :date, :price, :qty, :status, :stock_id, :kind, :chart
  belongs_to :stock
  default_scope { order('date ASC') }
  # mount_uploader :chart, ImageUploader  
  
	validates_presence_of :stock_id 
	validates_numericality_of :qty, :price
	before_create :assign_values	
	before_update :assign_values
  # Getter
  def amount
		qty * price
  end 
	
	private
	def assign_values
		self.fee = (self.qty * self.price) * 0.002070;
		self.vat = self.fee * 0.07;
		self.net = (self.qty * self.price) + self.fee + self.vat;
		if self.status != 'Sold'
			self.status = 'Active'
		end			
	end  
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render json: @buy, status: :created, location: @buy }
      else
        format.html { render action: "new" }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buys/1
  # PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:date, :price, :qty, :status, :stock_id, :kind, :chart)
    end  
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_form.html.erb
<%= form_for(@buy) do |f| %>
  <% if @buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% @buy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock_id %><br />
	<%= f.collection_select :stock_id, Stock.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :qty %><br />
    <%= f.number_field :qty %>
  </div>



  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :chart %><br />
    <%= f.file_field :chart %>
  </div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing buy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_buy_path %></li>
<% end %>
<%= currently_at 'Buys'%>

<h1>Listing buys</h1>

<table id="buys" class="display">
<thead>	
  <tr>
    <th>Status</th>  	
    <th>Stock</th>
    <th>Purchase Date</th>
    <th>Days</th>    
    <th>Qty</th>
    <th>Price</th>
    <th>Amount</th>  
    <th>Net</th>        
    <th>Kind</th>    
    <th>Id</th>      
    <th>Sell</th>            
  </tr>
</thead>
<tbody>
<% @buys.each do |buy| %>
  <tr>
    <td><%= buy.status %></td>  	
    <td><%= link_to(buy.stock.name, buy) %></td>
    <td><%= buy.date %></td>
    <td><%= (Date.today - buy.date).to_i %></td>    
    <td><%= number_with_delimiter(buy.qty) %></td>
    <td><%= number_to_currency(buy.price) %></td>    
    <td><%= number_to_currency(buy.amount) %></td>       
    <td><%= number_to_currency(buy.net) %></td>    
   <td><%= buy.kind %></td>    
   <td><%= buy.id %></td>   
   <td><%= link_to 'Sell', new_sell_path(:param1 => buy.id) %></td>       
  </tr>
<% end %>
</tbody>
</table>

app/views/buys/new.html.erb
<h1>New buy</h1>

<%= render 'form' %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_buy_path %></li>
<li><%= link_to 'Edit', edit_buy_path(@buy) %></li>
<li><%= link_to 'Back', buys_path %></li>
<li><%= link_to 'Destroy', @buy, method: :delete, data: { confirm: 'Are you sure?' } %></li>

<% end %>
<%= currently_at 'Buys'%>

<p>
  <b>Stock:</b>
  <%= @buy.stock.name %>
</p>

<p>
  <b>Date:</b>
  <%= @buy.date %>
</p>

<p>
  <b>Qty:</b>
  <%= number_with_delimiter(@buy.qty) %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@buy.price) %>
</p>

<p>
  <b>Fee:</b>
  <%= number_to_currency(@buy.fee) %>
</p>

<p>
  <b>VAT:</b>
  <%= @buy.vat %>
</p>
<p>
  <b>Net:</b>
  <%= number_to_currency(@buy.net) %>
</p>
<p>
  <b>Status:</b>
  <%= @buy.status %>
</p>
<p>
  <b>Kind:</b>
  <%= @buy.kind %>
</p>
<p>
  <b>Id:</b>
  <%= @buy.id %>
</p>
<p>
   <%#= image_tag @buy.chart_url.to_s %>
</p>