config/routes.rb
Portfolio::Application.routes.draw do

  resources :dividends

  resources :cover_buys

  resources :short_sells

  resources :sells

  resources :buys

  resources :stocks

  resources :categories

  get "pages/home"
	root :to => 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ActiveRecord::Base
  # attr_accessible :date, :price, :qty, :status, :stock_id, :kind, :chart
  belongs_to :stock
  default_scope { order('date ASC') }
  # mount_uploader :chart, ImageUploader  
  
	validates_presence_of :stock_id 
	validates_numericality_of :qty, :price
	before_create :assign_values	
	before_update :assign_values
  # Getter
  def amount
		qty * price
  end 
	
	private
	def assign_values
		self.fee = (self.qty * self.price) * 0.002070;
		self.vat = self.fee * 0.07;
		self.net = (self.qty * self.price) + self.fee + self.vat;
		if self.status != 'Sold'
			self.status = 'Active'
		end			
	end  
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :name, :sequence
  default_scope {order('sequence ASC') }
  
end

app/models/cover_buy.rb
class CoverBuy < ActiveRecord::Base
  #	attr_accessible :chart, :date, :days, :fee, :net, :percent, :price, :profit, :sequence, :vat, :yearly, :short_sell_id
  	
  	belongs_to :short_sell
  	default_scope { order('date DESC') }
  	mount_uploader :chart, ImageUploader  
  
	validates_presence_of :short_sell_id 
	validates_numericality_of :price

	before_save :assign_values
	after_save :assign_sequence
	before_destroy :deduct_values

  # Getter
	def amount
    	short_sell.qty * price
	end

	private
	def assign_values
		self.fee = (self.short_sell.qty * self.price) * 0.002070
		self.vat = self.fee * 0.07
		self.net = (self.short_sell.qty * self.price) + self.fee + self.vat
 		self.profit = self.short_sell.net - self.net
 		self.days = (self.date - self.short_sell.date).to_i 
 		if self.days == 0
    		self.days = 1
 		end
 		self.percent = (self.profit/self.net)*100
 		self.yearly = self.percent*365/self.days 
 
 		short_sell = ShortSell.find(self.short_sell_id)
		short_sell.status = 'Bought'
		short_sell.save
	
	end  

	def assign_sequence
		update_column(:sequence, 1000 - id)
	end

	def deduct_values		
 		short_sell = ShortSell.find(self.short_sell_id)
		short_sell.status = 'Active'
		short_sell.save		
	end  

end

app/models/dividend.rb
class Dividend < ApplicationRecord
  belongs_to :stock
  before_save :assign_names
  default_scope { order('year DESC, quarter DESC, name ASC') }

  YEAR = [
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016"]

  QUARTER = [
    "3",
    "2",
    "1",
  	"4"
  ]

  private

  def assign_names
		stock = Stock.find(self.stock_id)
    self.name = stock.name
    
		self.amt = (self.number * self.ppu);
		# self.x_date = self.p_date;

  end
end

app/models/sell.rb
class Sell < ActiveRecord::Base
 #	attr_accessible :buy_id, :date, :price, :fee, :vat, :net, :profit, :days, :percent, :yearly, :sequence, :chart

 	belongs_to :buy
 	default_scope { order('date DESC') }
 	mount_uploader :chart, ImageUploader  

	validates_presence_of :buy_id 
	validates_numericality_of :price

	before_save :assign_values
	after_save :assign_sequence
	before_destroy :deduct_values

  # Getter
	def amount
    	buy.qty * price
	end

	private
	def assign_values
		self.fee = (self.buy.qty * self.price) * 0.002070
		self.vat = self.fee * 0.07
		self.net = (self.buy.qty * self.price) - self.fee - self.vat
 		self.profit = self.net - self.buy.net
 		self.days = (self.date - self.buy.date).to_i 
 		if self.days == 0
    		self.days = 1
 		end
 		self.percent = (self.profit/self.buy.net)*100
 		self.yearly = self.percent*365/self.days 
 
 		buy = Buy.find(self.buy_id)
		buy.status = 'Sold'
		buy.save
	
	end  

	def assign_sequence
		update_column(:sequence, 1000 - id)
	end

	def deduct_values		
 		buy = Buy.find(self.buy_id)
		buy.status = 'Active'
		buy.save		
	end 
 
end

app/models/short_sell.rb
class ShortSell < ActiveRecord::Base
  belongs_to :stock
  # attr_accessible :chart, :date, :fee, :kind, :net, :price, :qty, :status, :stock_id, :vat
  default_scope { (order'date ASC') }
  mount_uploader :chart, ImageUploader  
  
	validates_presence_of :stock_id 
	validates_numericality_of :qty, :price
	before_create :assign_values	
	before_update :assign_values

  # Getter
  def amount
		qty * price
  end 
	
	private
	def assign_values
		self.fee = (self.qty * self.price) * 0.002070;
		self.vat = self.fee * 0.07;
		self.net = (self.qty * self.price) - self.fee - self.vat;
		if self.status != 'Bought'
			self.status = 'Active'
		end			
	end   
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  # attr_accessible :category_id, :name, :website
  belongs_to :category
  default_scope { order('name ASC') }
  
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render json: @buy, status: :created, location: @buy }
      else
        format.html { render action: "new" }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buys/1
  # PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:date, :price, :qty, :status, :stock_id, :kind, :chart)
    end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cover_buys_helper.rb
module CoverBuysHelper
end

app/helpers/dividends_helper.rb
module DividendsHelper
end

app/helpers/navigation_helper.rb
#---
# Excerpted from "The Rails View",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/warv for more book information.
#---
module NavigationHelper

  def nav_tab(title, url, options = {})
    current_tab = options.delete(:current)
    options[:class] = (current_tab == title) ? 'active' : 'inactive'
    content_tag(:li, link_to(title, url), options)
  end

  def currently_at(tab)
    render partial: 'layouts/main_nav', locals: {current_tab: tab}
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/short_sells_helper.rb
module ShortSellsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_footer.html.erb
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2013 Santi Soontarinka All Rights Reserved. All Wrongs Reversed.</p>
  </footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">

<%= link_to(
image_tag("logo.png",
alt: "Artflow",
id: "logo"),
title: "Dashboard") %>
<%= yield :main_navigation %>	




</header>

app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>
  <nav id="main_nav" role="navigation">
    <ul>
      <%= nav_tab 'Home',        root_path,        current: current_tab %>
      <%= nav_tab 'Buys',        buys_path,        current: current_tab %>
  	  <%= nav_tab 'Sells',       sells_path,       current: current_tab %>
  	  <%= nav_tab 'Dividends',   dividends_path,   current: current_tab %>
      <%= nav_tab 'Short Sells', short_sells_path, current: current_tab %>
      <%= nav_tab 'Cover Buys',  cover_buys_path,  current: current_tab %>    
  	  <%= nav_tab 'Stocks',      stocks_path,      current: current_tab %>      
      <%= nav_tab 'Categories',  categories_path,  current: current_tab %>     
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    <% if content_for?(:title) %>
      Portfolio: <%= yield :title %>
    <% else %>
      Portfolio
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png", alt: "Portfolio", id: "tagline") %>
  <div class="container">
    <section id="content">
      <%# START:notifications %>
      <% if notice %>
        <p class="notification notice">
          <%= notice %>
        </p>
      <% end %>

      <% if alert %>
        <p class="notification alert">
          <%= alert %>
        </p>
      <% end %>
      <%# END:notifications %>
      <%= yield %>
    </section>
    <section id="sidebar">
      <nav id="functional_nav">
        <ul>
          <%= yield :functional_nav %>
        </ul>
      </nav>
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
    <%#    <%= render partial: 'activity_items/recent' %> 
      </section>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<% currently_at 'Home' %>
<%= image_tag("portfolio.gif") %>